"""Initial migration

Revision ID: 32a0a99dd5a1
Revises: 
Create Date: 2025-04-28 20:24:14.807029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32a0a99dd5a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discipline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('lvl1',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lvl2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lvl3',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('placeholder_match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('placeholder_match_atoms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('task_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('course_variant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discipline_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['discipline_id'], ['discipline.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('placeholder_match_lvl2',
    sa.Column('placeholder_match_id', sa.Integer(), nullable=True),
    sa.Column('lvl2_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lvl2_id'], ['lvl2.id'], ),
    sa.ForeignKeyConstraint(['placeholder_match_id'], ['placeholder_match.id'], )
    )
    op.create_table('placeholder_match_lvl3',
    sa.Column('placeholder_match_atoms_id', sa.Integer(), nullable=True),
    sa.Column('lvl3_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lvl3_id'], ['lvl3.id'], ),
    sa.ForeignKeyConstraint(['placeholder_match_atoms_id'], ['placeholder_match_atoms.id'], )
    )
    op.create_table('section',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discipline_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['discipline_id'], ['discipline.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('template_lvl1',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('lvl1_id', sa.Integer(), nullable=True),
    sa.Column('always_eat', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['lvl1_id'], ['lvl1.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('layout_variant_1',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_lvl1_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('css_style', sa.Text(), nullable=False),
    sa.Column('html', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['template_lvl1_id'], ['template_lvl1.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('template_lvl2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_lvl1_id', sa.Integer(), nullable=True),
    sa.Column('lvl2_id', sa.Integer(), nullable=True),
    sa.Column('max_count_y', sa.Integer(), nullable=True),
    sa.Column('min_count_y', sa.Integer(), nullable=True),
    sa.Column('max_count_x', sa.Integer(), nullable=True),
    sa.Column('min_count_x', sa.Integer(), nullable=True),
    sa.Column('always_eat', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['lvl2_id'], ['lvl2.id'], ),
    sa.ForeignKeyConstraint(['template_lvl1_id'], ['template_lvl1.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['section.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('task_text', sa.String(length=120), nullable=True),
    sa.Column('variables', sa.Text(), nullable=True),
    sa.Column('coefficients', sa.Text(), nullable=True),
    sa.Column('restricts', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('layout_variant_2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_lvl2_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('css_style', sa.Text(), nullable=False),
    sa.Column('html', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['template_lvl2_id'], ['template_lvl2.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('task_type_id', sa.Integer(), nullable=False),
    sa.Column('course_variant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_variant_id'], ['course_variant.id'], ),
    sa.ForeignKeyConstraint(['task_type_id'], ['task_type.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('template_lvl3',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_lvl2_id', sa.Integer(), nullable=True),
    sa.Column('lvl3_id', sa.Integer(), nullable=True),
    sa.Column('always_eat', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['lvl3_id'], ['lvl3.id'], ),
    sa.ForeignKeyConstraint(['template_lvl2_id'], ['template_lvl2.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generation_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('issued', sa.Boolean(), nullable=False),
    sa.Column('results', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('layout_variant_3',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_lvl2_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('css_style', sa.Text(), nullable=False),
    sa.Column('html', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['template_lvl2_id'], ['template_lvl3.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_generator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('generator_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['generator_id'], ['generator.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generation_variant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('result_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['result_id'], ['generation_result.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('generation_variant')
    op.drop_table('task_generator')
    op.drop_table('layout_variant_3')
    op.drop_table('generation_result')
    op.drop_table('template_lvl3')
    op.drop_table('task')
    op.drop_table('layout_variant_2')
    op.drop_table('generator')
    op.drop_table('topic')
    op.drop_table('template_lvl2')
    op.drop_table('layout_variant_1')
    op.drop_table('template_lvl1')
    op.drop_table('section')
    op.drop_table('placeholder_match_lvl3')
    op.drop_table('placeholder_match_lvl2')
    op.drop_table('course_variant')
    op.drop_table('users')
    op.drop_table('template')
    op.drop_table('task_type')
    op.drop_table('placeholder_match_atoms')
    op.drop_table('placeholder_match')
    op.drop_table('lvl3')
    op.drop_table('lvl2')
    op.drop_table('lvl1')
    op.drop_table('discipline')
    # ### end Alembic commands ###
