"""Add lvl3_id column to TemplateLvl3 model

Revision ID: bc7e7f7098e1
Revises: 
Create Date: 2025-04-15 23:14:16.419445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc7e7f7098e1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('template_lvl3', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lvl3_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'lvl3', ['lvl3_id'], ['id'])
        batch_op.drop_column('lvl2_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('template_lvl3', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lvl2_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'lvl2', ['lvl2_id'], ['id'])
        batch_op.drop_column('lvl3_id')

    # ### end Alembic commands ###
