version: '3.8'

services:
  db:
    image: postgres:13.10
    env_file: ./expressionism-server/.env
    volumes:
      - pgdata:/var/lib/postgresql/data

  expressionism-server:
    build:
      context: ./expressionism-server
    command: gunicorn -w 4 -b 0.0.0.0:5000 config:app
    volumes:
      - ./expressionism-server:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file: ./expressionism-server/.env

volumes:
  pgdata:
