version: '3.8'

services:
  db:
    image: postgres:13.10
    env_file: ./expressionism-server/.env
    volumes:
      - pgdata:/var/lib/postgresql/data

  expressionism-server:
    build:
      context: ./expressionism-server
    command: gunicorn -w 4 -b 0.0.0.0:5000 config:app
    volumes:
      - ./expressionism-server:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file: ./expressionism-server/.env

  expressionism-dev:
    build:
      context: ./expressionism-server
    command: flask run --host=0.0.0.0 --port=5000
    volumes:
      - ./expressionism-server:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=development
    env_file: ./expressionism-server/.env

  expressionism-client-dev:
    build:
      context: ./expressionism-client
    volumes:
      - ./expressionism-client:app
    working_dir: /app
    ports:
      - "3000:3000"
    command: yarn dev
    

  expressionism-client:
    build:
      context: ./expressionism-client
    volumes:
      - ./expressionism-client:app  
    working_dir: /app
    ports:
      - "3000:3000"    

volumes:
  pgdata:
